export enum FieldsNames {
  FirstName = 'firstName',
  LastName = 'lastName',
  Email = 'email',
  PhoneNumber = 'phoneNumber',
  FacebookId = 'facebookId',
  InstagramId = 'instagramId',
  Password = 'password',
  IsTripOrganizer = 'isTripOrganizer',
  Image = 'image',
  Name = 'name',
  Location = 'location',
  Tags = 'tags',
  Price = 'price',
  Currency = 'currency',
  Including = 'including',
  AvailableDates = 'availableDates',
  StartTime = 'startTime',
  EndTime = 'endTime',
  Level = 'level',
  Duration = 'duration',
  DogFriendly = 'dogFriendly',
  Comments = 'comments',
  Amenities = 'amenities',
  Materials = 'materials',
  Description = 'description',
}
